#!/usr/bin/python
import subprocess
import os
import time
import sys

if len(sys.argv) < 2:
	date = time.strftime("%m-%y")
	file = "%s.text" % (date)
	subprocess.call(["gvim", "+", os.path.expanduser("~/Dropbox/life/logs/journal/" + file)])
elif sys.argv[1] == '+':
	date = time.strftime("%m-%y")
	file = "%s.text" % (date)
	fileName = os.path.expanduser("~/Dropbox/life/logs/journal/" + file)
	open(fileName, "a").write("* " + " ".join(sys.argv[2:]) + "\n")
else:
	file = "%s.text" % (sys.argv[1])
	fileName = os.path.expanduser("~/Dropbox/life/logs/journal/" + file)
	subprocess.call(["gvim", fileName])
