#!/usr/bin/python
import argparse
import os
import subprocess
import random

def openurl(name, url):
	print('opening: ' + name)
	subprocess.call(['chromium', url])

DEFAULT_FILE = '~/Dropbox/life/logs/notes/urls.text'

parser = argparse.ArgumentParser(description='Manage and work with bookmarks.')
parser.add_argument('-f', '--file', dest='inFile', help='input file', default=DEFAULT_FILE)
parser.add_argument('-n', '--num', type=int, dest='number', help='number to show', default=1)
parser.add_argument('-d', '--del', dest='delimiter', help='delimiter used in the file', default='|')
parser.add_argument('-r', '--random', dest='random', help='open a random url', action='store_true')
parser.add_argument('-a', '--add', dest='add', help='add url')
args = parser.parse_args()

theFile = os.path.expanduser(args.inFile)

if args.add:
	open(theFile, 'a').write(args.add)
else:
	lines = [line.strip() for line in open(theFile)]
	random = random.randrange(1,len(lines)) if args.random else 0
	count = 0
	for line in lines:
		count += 1
		url = line.split(args.delimiter)[1].strip();
		name = line.split(args.delimiter)[0].strip();
		if args.random:
			if count == random:
				openurl(name, url)
				break
		else:
			if count <= args.number:
				openurl(name, url)
			elif count > args.number:
				break
