#!/usr/bin/python
#-*-coding: UTF-8-*-

#author: Chad G Hansen
#note: built with python 2.7.2
#copyright: do whatever you want with it, just attribute me (Chad G Hansen).

#imports
import os
import sys
import argparse
import subprocess
import re

# set the todo.text file filename and path
todoFile = '~/Dropbox/todo.text'
todoFile = os.path.expanduser(todoFile)

parser = argparse.ArgumentParser(prog='./todo', description='A simple todo list manager.')
#command line arguments
parser.add_argument('-l', '--list', dest='list', action='store_true', default=False, help='Lists todo items.')
parser.add_argument('-s', '--search', dest='search_terms', default=[], nargs='+', help='Lists todo items that match the specified search terms.')
parser.add_argument('-t', '--tag-search', dest='tag_search_terms', default=[], nargs='+', help='Lists todo items that match the specified tags.')
parser.add_argument('-v', '--verbose', help='Verbose output on searching (both keyword and tags).', dest='verbose_output', default=False, action='store_true')
parser.add_argument('-n', '--next', dest='next', action='store_true', default=False, help='Displays the next item.');
parser.add_argument('-o', '--open', dest='open_with', default='', help='Opens the todo list in the editor specified.');
parser.add_argument('-a', '--add', dest='item_to_add', default='', help='Adds a new item to the bottom of the todo list.');
parser.add_argument('-d', '--done', dest='item_to_remove', default=0, type=int, metavar="NUM", help='Removes the specified item from the todo list.');
parser.add_argument('-p1', '--priority-1', dest='items_for_priority_1', default=0, type=int, metavar="NUM", help='Change priority on the specified item.');
parser.add_argument('-p2', '--priority-2', dest='items_for_priority_2', default=0, type=int, metavar="NUM", help='Change priority on the specified item.');
parser.add_argument('-p3', '--priority-3', dest='items_for_priority_3', default=0, type=int, metavar="NUM", help='Change priority on the specified item.');
parser.add_argument('-rp', '--remove-priority', dest='items_for_priority_0', default=0, type=int, metavar="NUM", help='Change priority on the specified item.');

args = parser.parse_args()

file = open(todoFile, "r")
todoList = file.read()
file.close()
todoList = todoList.splitlines()
nextItemNumber = 1
for item in todoList:
	if int(item[0:item.find('.')]) >= nextItemNumber:
		nextItemNumber = int(item[0:item.find('.')]) + 1


if args.next:
	file = open(todoFile, "r")
	print file.readline().strip()
	file.close()

elif args.list:
	file = open(todoFile, "r")
	print file.read().strip()
	file.close()

elif len(args.search_terms) > 0:
	searchTerms = ' '.join([term.lower().strip() for term in args.search_terms])
	results = ''
	if args.verbose_output:
		print 'Search for: ' + searchTerms
	for line in open(todoFile):
		if searchTerms in line.lower():
			results += line
	if results == '':
		results = "No items found."
	print results.strip()

elif len(args.tag_search_terms) > 0:
	searchTerms = ['#' + term.lower().strip() for term in args.tag_search_terms]
	results = ''
	if args.verbose_output:
		print 'Search for tags: ' + ' or '.join(searchTerms)
	for line in open(todoFile):
		for term in searchTerms:
			if term in line.lower():
				results += line
				break;
	if results == '':
		results = "No items found."
	print results.strip()

elif args.open_with != '':
	subprocess.call([args.open_with, todoFile])

elif args.item_to_add != '':
	appendText = " ".join(args.item_to_add)
	open(todoFile, "a").write(str(nextItemNumber) + '. ' + appendText + '\n')
	print "+ TODO: " + appendText

elif args.item_to_remove != 0:
	completeNumber = int(args.item_to_remove)
	resp = ''
	newFile = ''
	for line in open(todoFile):
		if int(line[0:line.find('.')]) == completeNumber:
			resp = line	
		else:
			newFile += line
	if resp == '':
		resp = 'No item found.'
	else:
		open(todoFile, 'w').write(newFile)
	print "- DONE: " + resp.strip()

elif args.items_for_priority_1 != 0 or args.items_for_priority_2 != 0 or args.items_for_priority_3 != 0 or args.items_for_priority_0 != 0:
	priority = ''
	itemNumber = 0
	if args.items_for_priority_1 != 0:
		priority = '(A)'
		item_number = args.items_for_priority_1
	elif args.items_for_priority_2 != 0:
		priority = '(B)'
		item_number = args.items_for_priority_2
	elif args.items_for_priority_3 != 0:
		priority = '(C)'
		item_number = args.items_for_priority_3
	elif args.items_for_priority_0 != 0:
		priority = '0'
		item_number = args.items_for_priority_0

	resp = ''
	newFile = ''
	for line in open(todoFile):
		if int(line[0:line.find('.')]) == itemNumber:
			if priority != '0' and priority != '': #adding a priority
				resp = line.replace(str(itemNumber) + ". ", str(itemNumber) + ". " + priority + " ")
				newFile += resp
			elif priority == '0': #taking away the priority
				resp = re.sub(r'\.\s\(.\)\s', '. ', line)
				newFile += resp
		else:
			newFile += line
	if resp == '':
		resp = 'No item found.'
	else:
		open(todoFile, 'w').write(newFile)
	print "+ PRI: " + resp.strip()

